fix RtD build by using mock import
Mock list taken from Raven to avoid having to discover them one by one.

Previous fix reverting to use existing environment.yml did not work,
have the following errors:

https://readthedocs.org/projects/finch/builds/11114170/
```
 python /home/docs/checkouts/readthedocs.org/user_builds/finch/conda/refresh-cookiecutter-template-using-cruft/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v3.0.3
loading translations [en]... done
/home/docs/checkouts/readthedocs.org/user_builds/finch/conda/refresh-cookiecutter-template-using-cruft/lib/python3.8/site-packages/sphinx/deprecation.py:52: RemovedInSphinx40Warning: sphinx.builders.html.DirectoryHTMLBuilder is deprecated. Check CHANGES for Sphinx API modifications.
  return getattr(self._module, name)
/home/docs/checkouts/readthedocs.org/user_builds/finch/conda/refresh-cookiecutter-template-using-cruft/lib/python3.8/site-packages/readthedocs_ext/readthedocs.py:14: RemovedInSphinx40Warning: sphinx.builders.html.SingleFileHTMLBuilder is deprecated. Check CHANGES for Sphinx API modifications.
  from sphinx.builders.html import (DirectoryHTMLBuilder, SingleFileHTMLBuilder,

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/finch/conda/refresh-cookiecutter-template-using-cruft/lib/python3.8/site-packages/sphinx/registry.py", line 402, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/finch/conda/refresh-cookiecutter-template-using-cruft/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nbsphinx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/finch/conda/refresh-cookiecutter-template-using-cruft/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/finch/conda/refresh-cookiecutter-template-using-cruft/lib/python3.8/site-packages/sphinx/application.py", line 244, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/finch/conda/refresh-cookiecutter-template-using-cruft/lib/python3.8/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/finch/conda/refresh-cookiecutter-template-using-cruft/lib/python3.8/site-packages/sphinx/registry.py", line 405, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension nbsphinx (exception: No module named 'nbsphinx')

Extension error:
Could not import extension nbsphinx (exception: No module named 'nbsphinx')
```