drop 'crs' coordinate, writing it to disk causes issues
File ".../python3.8/site-packages/xarray/backends/api.py", line
205, in check_attr
    raise TypeError(
TypeError: Invalid value for attr: +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs lon_wrap=180 +type=crs must be a number, a string, an ndarray or a list/tuple of numbers/strings for serialization to
netCDF files