finch-usage.ipynb: have to use NBVAL_IGNORE_OUTPUT so same cell output works both for Jenkins and Github actions
Jenkins have slightly older version of various libraries so that might
explain the difference.

Error on Github actions after Jenkins is fixed in previous commit:
```
=================================== FAILURES ===================================
_______________ docs/source/notebooks/finch-usage.ipynb::Cell 1 ________________
Notebook cell execution failed
Cell 1: Cell outputs differ

Input:
help(wps.frost_days)

Traceback:
 mismatch 'stdout'

 assert reference_output == test_output failed:

  'Help on meth...ut files.\n\n' == 'Help on meth...ut files.\n\n'
    Help on method frost_days in module birdy.client.base:

    frost_days(tasmin=None, thresh='0 degC', freq='YS', month=None, season=None, check_missing='any', missing_options=None, cf_compliance='warn', data_validation='raise', variable=None, output_name=None, output_format='netcdf', csv_precision=None, output_formats=None) method of birdy.client.base.WPSClient instance
        Number of days where daily minimum temperatures are below a threshold temperature.

        Parameters
        ----------
        tasmin : ComplexData:mimetype:`application/x-netcdf`, :mimetype:`application/x-ogc-dods`
            NetCDF Files or archive (tar/zip) containing netCDF files. Minimum surface temperature.
        thresh : string
            Freezing temperature.
        freq : {'YS', 'MS', 'QS-DEC', 'AS-JUL'}string
            Resampling frequency.
        month : {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', ...}integer
            Months of the year over which to compute indicator.
        season : {'DJF', 'MAM', 'JJA', 'SON'}string
            Climatological season over which to compute indicator.
        check_missing : {'any', 'wmo', 'pct', 'at_least_n', 'skip', 'from_context'}string
            Method used to determine which aggregations should be considered missing.
        missing_options : ComplexData:mimetype:`application/json`
            JSON representation of dictionary of missing method parameters.
        cf_compliance : {'log', 'warn', 'raise'}string
            Whether to log, warn or raise when inputs have non-CF-compliant attributes.
        data_validation : {'log', 'warn', 'raise'}string
            Whether to log, warn or raise when inputs fail data validation checks.
        variable : string
  +         ...,
  +         [231., 225., ..., 189., 134.],
  +         [259., 258., ..., 186., 140.]],
  +
  +        ...,
  +
  +        [[122., 111., ...,   0.,   0.],
  +         [151., 153., ...,  80.,  43.],
  +         ...,
  +         [221., 220., ..., 140.,  94.],
  +         [246., 247., ..., 137., 107.]],
  +
  +        [[105.,  98., ...,   3.,   1.],
  +         [163., 172., ...,  91.,  59.],
  +         ...,
  +         [225., 225., ..., 161., 107.],
  +         [251., 250., ..., 156., 103.]]])
    Coordinates:
        height   float64 ...
  +   * time     (time) object/DATE/TIME/.../DATE/00:00:00
      * lat      (lat) float64 42.68 46.39 50.1 53.81 57.52 61.23
      * lon      (lon) float64 281.2 285.0 288.8 292.5 296.2 300.0 303.8
  -   * time     (time) object/DATE/TIME/.../DATE/00:00:00
    Attributes:
        units:          days
        cell_methods:   time: minimum (interval: 30 minutes) time: sum over days
        history:        tas=max(195,tas) applied to raw data; min of 194.73 detec...
        standard_name:  days_with_air_temperature_below_threshold
        long_name:      Number of frost days (tmin < 0 degc)
        description:    Annual number of days with minimum daily temperature belo...

=============================== warnings summary ===============================
../../../micromamba-root/envs/finch/lib/python3.10/site-packages/_pytest/config/__init__.py:1240
  /home/runner/micromamba-root/envs/finch/lib/python3.10/site-packages/_pytest/config/__init__.py:1240: PytestRemovedIn8Warning: The --strict option is deprecated, use --strict-markers instead.
    self.issue_config_time_warning(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED docs/source/notebooks/finch-usage.ipynb::Cell 1
FAILED docs/source/notebooks/finch-usage.ipynb::Cell 4
======== 2 failed, 36 passed, 2 skipped, 1 warning in 77.34s (0:01:17) =========
make: *** [Makefile:129: test-notebooks] Error 1
Error: Process completed with exit code 2.
```