notebooks: run make refresh-notebooks to fix make test-notebooks
Fix the following `make test-notebooks` error:

```
====================================================================== FAILURES ======================================================================
___________________________________________________ docs/source/notebooks/dap_subset.ipynb::Cell 9 ___________________________________________________
Notebook cell execution failed
Cell 9: Cell outputs differ

Input:
resp = wps.sdii(pr + sub)
out = resp.get(asobj=True)
out.output_netcdf.sdii

Traceback:
Missing output fields from running code: {'stdout'}

__________________________________________________ docs/source/notebooks/finch-usage.ipynb::Cell 1 ___________________________________________________
Notebook cell execution failed
Cell 1: Cell outputs differ

Input:
help(wps.frost_days)

Traceback:
 mismatch 'stdout'

 assert reference_output == test_output failed:

  'Help on meth...ut files.\n\n' == 'Help on meth...ut files.\n\n'
    Help on method frost_days in module birdy.client.base:

  - frost_days(tasmin=None, missing_options=None, check_missing='any', freq='YS', variable=None) method of birdy.client.base.WPSClient instance
  + frost_days(tasmin=None, missing_options=None, check_missing='any', freq='YS', variable=None, output_formats=None) method of birdy.client.base.WPSClient instance
  ?                                                                                            +++++++++++++++++++++
        Number of days where daily minimum temperatures are below 0.

        Parameters
        ----------
        tasmin : ComplexData:mimetype:`application/x-netcdf`, :mimetype:`application/x-ogc-dods`
            NetCDF Files or archive (tar/zip) containing netCDF files.
        freq : {'YS', 'MS', 'QS-DEC', 'AS-JUL'}string
            Resampling frequency; Defaults to "YS" (yearly).
        check_missing : {'any', 'wmo', 'pct', 'at_least_n', 'skip', 'from_context'}string
            Method used to determine which aggregations should be considered missing.
        missing_options : ComplexData:mimetype:`application/json`
            JSON representation of dictionary of missing method parameters.
        variable : string
            Name of the variable in the NetCDF file.

        Returns
        -------
        output_netcdf : ComplexData:mimetype:`application/x-netcdf`
            The indicator values computed on the original input grid.
        output_log : ComplexData:mimetype:`text/plain`
            Collected logs during process run.
        ref : ComplexData:mimetype:`application/metalink+xml; version=4.0`
            Metalink file storing all references to output files.

__________________________________________________ docs/source/notebooks/finch-usage.ipynb::Cell 4 ___________________________________________________
Notebook cell execution failed
Cell 4: Cell outputs differ

Input:
out = resp.get(asobj=True)

Traceback:
Missing output fields from running code: {'stdout'}

================================================================== warnings summary ==================================================================
/home/lvu/.conda/envs/finch/lib/python3.8/site-packages/nbval/plugin.py:115
/home/lvu/.conda/envs/finch/lib/python3.8/site-packages/nbval/plugin.py:115
  /home/lvu/.conda/envs/finch/lib/python3.8/site-packages/nbval/plugin.py:115: PytestDeprecationWarning: direct construction of IPyNbFile has been deprecated, please use IPyNbFile.from_parent
    return IPyNbFile(path, parent)

/home/lvu/.conda/envs/finch/lib/python3.8/site-packages/nbval/plugin.py:311: 16 tests with warnings
  /home/lvu/.conda/envs/finch/lib/python3.8/site-packages/nbval/plugin.py:311: PytestDeprecationWarning: direct construction of IPyNbCell has been deprecated, please use IPyNbCell.from_parent
    yield IPyNbCell('Cell ' + str(cell_num), self, cell_num,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================================== short test summary info ===============================================================
FAILED docs/source/notebooks/dap_subset.ipynb::Cell 9
FAILED docs/source/notebooks/finch-usage.ipynb::Cell 1
FAILED docs/source/notebooks/finch-usage.ipynb::Cell 4
===================================================== 3 failed, 13 passed, 18 warnings in 15.43s =====================================================
```